#include "snore_core/time/time_type.h"

using namespace godot;

// FIXME: LEFT OFF HERE: FINISH PORTING ---------------------------------------

void TimeType::_bind_methods() {
	BIND_ENUM_CONSTANT(APP_PHYSICS);
	BIND_ENUM_CONSTANT(APP_CLOCK);
	BIND_ENUM_CONSTANT(APP_PHYSICS_SCALED);
	BIND_ENUM_CONSTANT(APP_CLOCK_SCALED);
	BIND_ENUM_CONSTANT(APP_PHYSICS_FRAME_COUNT);
	BIND_ENUM_CONSTANT(APP_RENDER_FRAME_COUNT);
	BIND_ENUM_CONSTANT(PLAY_PHYSICS);
	BIND_ENUM_CONSTANT(PLAY_RENDER);
	BIND_ENUM_CONSTANT(PLAY_PHYSICS_SCALED);
	BIND_ENUM_CONSTANT(PLAY_RENDER_SCALED);
	BIND_ENUM_CONSTANT(PLAY_PHYSICS_FRAME_COUNT);
	BIND_ENUM_CONSTANT(PLAY_RENDER_FRAME_COUNT);
}
